account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('staff_sign_up/', views.StaffSignUpView.as_view(), name='Staff_signup'),
    path('customer_sign_up/', views.CustomerSignUpView.as_view(), name='Customer_signup'),
    path('login/', views.UserLoginView.as_view(), name='User_login'),
    path('logout/', views.UserLogoutView.as_view(), name='User_logout'),
    path('staff_profile/<int:user_id>', views.StaffProfileView.as_view(), name='Staff_profile'),
    path('user_profile/<int:user_id>', views.CustomUserProfileView.as_view(), name='user_profile'),
    path('update_profile/<int:user_id>', views.CustomerProfileUpdateView.as_view(), name='update_profile'),
    path('Staff_update_profile/<int:user_id>', views.StaffProfileUpdateView.as_view(), name='Staff_update_profile'),
    path('reset_pass/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_completed'),
    path('about/', views.AboutUsView.as_view(), name='about_us'),
]

cafe/urls.py
from django.urls import path
from .views import *


app_name = 'cafe'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('menu/', CategoryItems.as_view(), name='menu'),
    path('detail_item/<int:pk>/', DetailItemView.as_view(), name='detail_item'),

    path('cart/', CartView.as_view(), name='cart'),
    path('cart-receipt/<str:status>/', ReceiptView.as_view(), name='cart-receipt'),
    path('payment/<str:status>/', PaymentView.as_view(), name='payment_paid'),
    path('item-tag/<slug:tag_slug>/', ItemByTag.as_view(), name="items_by_tag"),
    path('item-category/<str:cat_name>/', FilterCategory.as_view(), name="cat_item"),
    path('delete-item-from-cart/', DeleteCartItemView.as_view(), name='delete_item_from_cart'),
    path('create_like/<int:pk>/', CreateLikeView.as_view(), name='create_like'),
    path('delet_like/<int:pk>/', DeleteLikeView.as_view(), name='delet_like'),
    path('best_items/', BestItemsView.as_view(), name='best_items'),
    path('json_check_like/<int:pk>/', LikeStatus.as_view(), name='check_like')

]

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cafe.urls', namespace='cafe')),
    path('account/', include('account.urls', namespace='account')),

 ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<footer class="ftco-footer ftco-section img">
    	<div class="overlay"></div>
      <div class="container">
        <div class="row mb-5">
          <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About Us</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 mb-5 mb-md-5">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Recent Blog</h2>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_2.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
             <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Services</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Cooked</a></li>
                <li><a href="#" class="py-2 d-block">Deliver</a></li>
                <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
                <li><a href="#" class="py-2 d-block">Mixed</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
{#  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>#}
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

          </div>
        </div>
      </div>
    </footer>
    

templates/partials/loader.html
<!-- loader -->
{% load static %}
{#  <div id="ftco-loader" class="show fullscreen"></div>#}
{#<svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg>#}


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  
{#  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>#}
{#  <script src="{% static 'js/google-map.js' %}"></script>#}
  <script src="{% static 'js/main.js' %}"></script>
  

templates/partials/navigation.html
    <!--  nav -->
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container m-2">
	      <a class="navbar-brand" href="{% url 'cafe:index' %}">Coffee<small>BigBoSs</small></a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
{#                index.html#}
                <li class="nav-item active" ><a href="{% url 'cafe:index' %}" class="nav-link">Home</a></li>
{#                menu.html#}
	           <li class="nav-item"><a href="{% url 'cafe:menu' %}" class="nav-link">Menu</a></li>

{#                services.html#}
	          <li class="nav-item"><a href="#" class="nav-link">Services</a></li>
{#                blog.html#}
	          <li class="nav-item"><a href="/best_items/" class="nav-link">Best Itemes</a></li>
{#                about.html#}
	          <li class="nav-item"><a href="#" class="nav-link">About</a></li>
	          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
{#                  shop.html#}
              	<a class="dropdown-item" href="#">Shop</a>
{#                  product-single.html#}
                <a class="dropdown-item" href="#">Single Product</a>
{#                  cart.html#}
                <a class="dropdown-item" href="{% url 'cafe:cart' %}">Cart</a>
                {% if user.is_authenticated %}
                <a class="dropdown-item" href="">Checkout</a>
                  {% endif %}

              </div>
              </li>
              <li class="nav-item dropdown">
{#                   Join us.html#}
               <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Join Us</a>
               <div class="dropdown-menu" aria-labelledby="dropdown04">
{#                   signup Staff.html#}
               	<a class="dropdown-item" href="{% url 'account:Staff_signup' %}">Job application form</a>
{#                   logout.html#}
                {% if user.is_authenticated %}
                <form action="{% url 'account:User_logout' %}" method="post" class="dropdown-item">{% csrf_token %}<input  class="logout" style="color:grey;" type="submit" value="log out" ></form>
                {% endif %}
{#                    signup Customer.html#}
                <a class="dropdown-item" href="{% url 'account:Customer_signup' %}">SignUp As Customer</a>
{#                   login.html#}
               {% if not user.is_authenticated %}
                 <a class="dropdown-item" href="{% url 'account:User_login' %}" >Log in</a>
               {% endif %}
               </div>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
{#                   Join us.html#}
               <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">BigBosS Team</a>
               <div class="dropdown-menu" aria-labelledby="dropdown04">
{#                   Collaborators' profiles.html#}
               <a href="{% url 'account:Staff_profile' user.id  %}" class="dropdown-item">Collaborators' profiles</a>
{#                   Customuser profile.html#}
               	<a href="{% url 'account:about_us' %}" class="dropdown-item">About Us</a>
               </div>
              </li>
              {% endif %}
{#                contact.html#}
	          <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
{#                cart.html#}
              <li class="nav-item cart "><a href="#" class="nav-link"><span class="icon icon-shopping_cart"></span><span class="bag d-flex justify-content-center align-items-center p-1"><small>1</small></span></a></li>
	        </ul>
	      </div>
		  </div>
          <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated  %}
                <li class="nav-item"> <button class="btn btn-dark m-4"style="background-color: rgba(44,44,44,0.7);width: 200px;" ><a href="{% url 'account:user_profile' user.id  %}">{{ user.firstname }} {{ user.lastname }}</a></button></li>
              {% endif %}
          </ul>
	  </nav>
    <!-- END nav -->