cafe/urls.py
from django.urls import path
from .views import *


app_name = 'cafe'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('menu/', CategoryItems.as_view(), name='menu'),
    path('detail_item/<int:pk>/', DetailItemView.as_view(), name='detail_item'),

    path('cart/', CartView.as_view(), name='cart'),
    path('cart-receipt/<str:status>/', ReceiptView.as_view(), name='cart-receipt'),
    path('payment/<str:status>/', PaymentView.as_view(), name='payment_paid'),
    path('item-tag/<slug:tag_slug>/', ItemByTag.as_view(), name="items_by_tag"),
    path('item-category/<str:cat_name>/', FilterCategory.as_view(), name="cat_item"),
    path('delete-item-from-cart/', DeleteCartItemView.as_view(), name='delete_item_from_cart'),
    path('create_like/<int:pk>/', CreateLikeView.as_view(), name='create_like'),
    path('delet_like/<int:pk>/', DeleteLikeView.as_view(), name='delet_like'),
    path('best_items/', BestItemsView.as_view(), name='best_items'),
    path('json_check_like/<int:pk>/', LikeStatus.as_view(), name='check_like')

]

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cafe.urls', namespace='cafe')),
    path('account/', include('account.urls', namespace='account')),

 ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe/forms/detail_view_form.py
from django import forms
from core.models import Comment

class CommentForm(forms.ModelForm):
   class Meta:
      model=Comment
      fields=["content"]
      widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control'}),
        }
      

cafe/forms/receipt_form.py
from django.contrib.auth import get_user_model
from django import forms
from cafe.models import Receipt
import datetime as dt
import requests

user = get_user_model()


class PersonalInfo(forms.ModelForm):
    user_address = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'House number and street name',
        'rows': '2',
    }), max_length=100, required=True)
    user_postcode = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''}),
                                    required=True, help_text="postcode should be number and 10 characters")
    user_city = forms.ChoiceField(choices=[], widget=forms.Select(attrs={'class': 'form-control'}),
                                  required=True)

    class Meta:
        model = user
        fields = ["firstname", "lastname", "phonenumber", "email"]
        widgets = {
            'phonenumber': forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': ''}),
            'firstname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''}),
            'lastname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_city'].choices = self.get_city_choices()

    @staticmethod
    def get_city_choices():
        url = 'https://countriesnow.space/api/v0.1/countries/cities'
        data = {
            "country": "Iran"
        }
        headers = {
            'Content-Type': 'application/json'
        }
        response = requests.post(url, json=data, headers=headers)
        if response.status_code == 200:
            cities_data = response.json()
            cities_choices = [(city[1:], city[1:]) for city in cities_data['data']]
            return cities_choices
        else:
            print(f"Error: {response.status_code} - {response.text}")
            return []

    def clean_user_postcode(self):
        user_postcode = self.cleaned_data.get('user_postcode')
        if len(user_postcode) > 10:
            raise forms.ValidationError("'postcode must be 10 characters'")
        elif not user_postcode.isnumeric():
            raise forms.ValidationError("'postcode must be integer'")
            # self._errors['user_postcode'] = self.error_class([
            #     'postcode must integer'])
        return user_postcode


class DeliveryTime(forms.ModelForm):
    HOUR_CHOICES = [(dt.time(hour=x), '{:02d}:00'.format(x)) for x in range(8, 21)]

    DAY_SELECTION = (
        ("sat", "Saturday"),
        ("sun", "Sunday"),
        ("mon", "Monday"),
        ("tues", "Tuesday"),
        ("wed", "Wednesday"),
        ("fri", "Friday"),
    )
    delivery_date = forms.CharField(label="pick the day",
                                    widget=forms.Select(choices=DAY_SELECTION, attrs={'class': 'form-control', "style":"background-color: transparent !important;"}))
    delivery_time = forms.TimeField(label="pick the time",
                                    widget=forms.Select(choices=HOUR_CHOICES, attrs={'class': 'form-control'}))

    class Meta:
        model = Receipt
        fields = ['delivery_date', 'delivery_time']

cafe/forms/search_form.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(label=False,)

cafe/views.py
from django.shortcuts import render
import json
from json import JSONDecodeError
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, Http404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from psycopg2 import OperationalError
from django.views.generic import ListView, View, CreateView, TemplateView, FormView, UpdateView
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from core.models import Image, Comment
from .forms import search_form, receipt_form, detail_view_form
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest
from .models import *
from django.http import JsonResponse
from taggit.models import Tag

user = get_user_model()


class ContextMixin():
    def get_context(self, session_data):
        context = {}

        try:

            context = {
                'item_data': session_data,
                'item_total': 0,
                'subtotal': 0,
                'total': 0,
                'discount_total': 0,
                'delivery_cost': 0,
            }
            for item in session_data:
                quantity = item.get('quantity', 0)
                price = item.get('price', 0)
                discount = item.get('discount', 0)
                item_total = int(quantity) * price - discount
                item['item_total'] = item_total
                context['discount_total'] += discount
                context['subtotal'] += item_total
                context['delivery_cost'] = item_total * 2
            context['total'] = context['subtotal'] + context['delivery_cost']


        except OrderItem.DoesNotExist:
            context['error'] = "Order Items does not exist"
        except Order.DoesNotExist:
            context['error'] = "Order does not exist"

        return context

    @staticmethod
    def item_search(request):
        items = Items.objects.none()
        form = search_form.SearchForm()
        if "search" in request.GET:
            items = Items.objects.all()
            form = search_form.SearchForm(request.GET)
            if form.is_valid():
                try:
                    cd = form.cleaned_data["search"]
                    items = (items.annotate(similarity=Greatest(
                        TrigramSimilarity("title", cd),
                        TrigramSimilarity("description", cd), ))
                             .filter(similarity__gt=0.1).order_by("-similarity"))
                except OperationalError:
                    messages.error("operational error", "danger")
                    items = []

        context = {
            "search_form": form,
            "items": items

        }
        return context


class SimilarityItemMixin:
    def get_similar_data(self, item_id):
        current_item = get_object_or_404(Items, id=item_id)
        item_tags_ids = current_item.tags.values_list('id', flat=True)
        similar_item = Items.objects.filter(tags__in=item_tags_ids).exclude(id=item_id)
        similar_item = similar_item.annotate(same_tags=Count('tags')).order_by('-same_tags', '-price')[:4]
        context = {
            'item': current_item,
            'similar_item': similar_item,
        }
        return context


class CartView(ContextMixin, SimilarityItemMixin, View):
    template_name = "cart.html"

    def get(self, request, *args, **kwargs):

        session_order = request.session.get('order', [])

        self.context = self.get_context(session_order) if session_order else {
            'error': "Order does not exist"}
        item_ids = [item['id'] for item in session_order]

        self.context["images"] = Image.objects.filter(content_type=ContentType.objects.get_for_model(Items))
        if item_ids:
            self.similarity_item = self.get_similar_data(item_ids[0])
            self.context['similarity_item'] = self.similarity_item
        return render(request, self.template_name, self.context)

    @staticmethod
    def post(request, *args, **kwargs):
        try:

            new_order = json.loads(request.body)
            session_order = request.session.get('order', [])
            list_id = [item.get("id") for item in session_order]

            is_exist = False

            for item in session_order:
                if item['id'] == new_order['id']:
                    is_exist = True

                    item['quantity'] = int(item['quantity']) + int(new_order['quantity'])
                    break
            if not is_exist:
                session_order.append(new_order)
            request.session['order'] = session_order
            request.session.modified = True
            return JsonResponse({'message': 'Order has been added successfully'})
        except JSONDecodeError as e:
            return JsonResponse({'error': str(e)}, status=400)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)


class ReceiptView(LoginRequiredMixin, UpdateView, ContextMixin):
    model = user
    template_name = 'checkout.html'
    form_class = receipt_form.PersonalInfo
    success_url = reverse_lazy("cafe:cart-receipt", args={"status": "payment"})
    success_message = "Your information has been successfully registered"

    # def get_success_url(self):
    #     return reverse("cafe:cart-receipt", kwargs={'status': "payment"})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, "You must be logged in", "danger")
            return redirect("account:User_login")

        self.user_id = self.request.user.id
        order, created = Order.objects.get_or_create(user_id=self.user_id)
        order.status = "payment"
        order.save()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, query_set=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session_order = self.request.session.get('order', [])
        context.update({
            'session_data': self.get_context(session_order) if session_order else
            {'error': "Order does not exist"},
            'all_tag': Tag.objects.values_list('name', flat=True).distinct(),
            "search": self.item_search(self.request),
            "category_item_counts": CategoryMenu.objects.annotate(item_count=Count('items')),
            'delivery_form': receipt_form.DeliveryTime
        })

        return context


class PaymentView(LoginRequiredMixin, ContextMixin, CreateView):
    template_name = "payment_done.html"
    model = Receipt
    form_class = receipt_form.DeliveryTime

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, "You must be logged in", "danger")
            return redirect("account:User_login")
        self.user_id = request.user.id
        self.order_instance = get_object_or_404(Order, user_id=self.user_id)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):

        session_order = request.session.get('order', [])
        context = self.get_context(session_order) if session_order else {
            'error': "Order does not exist"}

        OrderItem.objects.filter(order=self.order_instance).delete()

        for item in session_order:
            order_item = OrderItem(order=self.order_instance)
            order_item.quantity = item.get("quantity", 1)
            order_item.delivery_cost = item.get("delivery_cost", 0)
            order_item.save()

            item_id = item.get('id', [])
            item_instance = Items.objects.get(id=item_id)
            order_item.items.add(item_instance)
            order_item.save()

        # del self.request.session['order']
        sessionStorage.clear()


        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        delivery_time_form = receipt_form.DeliveryTime(request.POST)
        if delivery_time_form.is_valid():
            cd = delivery_time_form.cleaned_data.items()

            delivery_time = delivery_time_form.save(commit=False)
            order_item = Order.objects.create(status="paid")
            order_item.delivery_times.add(delivery_time)
            return render(request, self.template_name)
        return redirect(request, "cafe:payment_paid' 'paid")



class FilterCategory(ListView):
    template_name = "cat_item.html"
    context_object_name = 'cat_item'
    model = Items

    def get_queryset(self):
        self.category_name = self.kwargs['cat_name']
        queryset = Items.objects.filter(category_id__title=self.category_name)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_name'] = self.category_name
        context["images"] = Image.objects.filter(content_type=ContentType.objects.get_for_model(Items))
        return context


class ItemByTag(ListView):
    template_name = "tag_items.html"
    model = Items

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = None
        select_item = Items.objects.all()
        if tag_slug := self.kwargs.get('tag_slug'):
            tag = get_object_or_404(Tag, slug=tag_slug)
            select_item = Items.objects.filter(tags__in=[tag])

        context = {
            'images' : Image.objects.filter(content_type=ContentType.objects.get_for_model(Items)),
            'select_item': select_item,
            'tags': tag,
        }
        return context


class DeleteCartItemView(View):
    template_name = "cart.html"

    def post(self, request, *args, **kwargs):

cafe/templates/best_items.html
{% extends "base.html" %}
{% load static %}
{% block title %}cart{% endblock %}
{% block content %}
{% comment %} best_items={id:[queryset]} {% endcomment %}
{% comment %} <h1>{{best_items}}</h1> {% endcomment %}






{% comment %} <div class="row"> {% endcomment %}
    {% for cat, queryset  in best_items.items %}
    <div class="d-flex justify-content-center " style="margin-top: 100px;
    margin-bottom: 100px">
        <h2>{{cat.title}}</h2>
    </div>
<div class="row justify-content-center align-items-cente">

        
                {% for item in queryset %}
                    
                        <div class="col-md-3 text-center">
                            <div class="menu-wrap">
                                {% for image in images %}
                                {% comment %} <h1>{{item.id }}    {{image.object_id}}</h1> {% endcomment %}
                                    {% if image.object_id == item.id %}
                                        <a href="#" class="menu-img img mb-4" ><img src="{{image.image.url }} "class="img-fluid menu-img img mb-4" alt="Colorlib Template"></a>
                                    {% endif %}
                                {% endfor %}
                                    <div class="text">
                                        <h3><a href="#">{{item.title}}</a></h3>
                                        <p>{{item.description}}</p>
                                        <p class="price"><span>{{item.price}}</span></p>
                                        <p class="price"><span>{{item.like.all.count}}</span></p>
                                        <p><a href={% url 'cafe:detail_item' item.id %} class="btn btn-primary btn-outline-primary">see more</a></p>
                                    </div>
                            </div>
                        </div>
                    
                {% endfor %}
</div>
    {% endfor %}
{% comment %} </div> {% endcomment %}

{% endblock %}

cafe/templates/cat_item.html
{% extends "base.html" %}
{% load static %}
{% block title %}cart{% endblock %}
{% block content %}

 <section class="ftco-section">
    	<div class="container">
        <div class="row">

        	<div class="col-md-6 mb-5 mt-5 pb-3">
        		<h3 class="mb-5 heading-pricing ftco-animate">{{cat_name.title}}</h3>
                {% for item in cat_item %}
        		<div class="pricing-entry d-flex ftco-animate">
							{% for image in images %}
                                    {% if image.object_id == item.id %}

									 <td class="image-prod"><div class="img" ><img src="{{image.image.url}}" class="img" alt="item picture"></div></td>
                                    {% endif %}
                                {% endfor %}


        			<div class="desc pl-3">
	        			<div class="d-flex text align-items-center">

	        				<a href="{% url 'cafe:detail_item' item.id %}"><h3><span>{{item.title}}</span></h3></a>
	        				<span class="price">${{item.price}}</span>
	        			</div>
	        			<div class="d-block">
	        				<p>{{item.description|truncatechars:80}}</p>
	        			</div>
        			</div>

        		</div>
						{% empty %}
		<h1>you have no categorys</h1>
        {% endfor %}
        	</div>

        </div>
    	</div>





    </section>
{% endblock %}

cafe/templates/checkout.html
{% extends "base.html" %}
{% load static %}
{%  block title %}{% endblock %}
{%  block content %}

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Checkout</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'cafe:index' %}">Home</a></span> <span>Checout</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-xl-8 ftco-animate">
						<form action="{% url 'cafe:cart-receipt' 'payment' %}" class="billing-form ftco-bg-dark p-3 p-md-5" method="post" novalidate>
							<h3 class="mb-4 billing-heading">Billing Details</h3>
	          	<div class="row align-items-end">
	          		<div class="col-md-6">
	                <div class="form-group">
                        {% csrf_token %}

	                	<label >Firt Name</label>
						{{ form.firstname }}
	                </div>
	              </div>
	              <div class="col-md-6">
	                <div class="form-group">
	                	<label >Last Name</label>
						{{form.lastname}}

	                </div>
                </div>
                <div class="w-100"></div>
		            <div class="col-md-12">
		            	<div class="form-group">
		            		<label >City</label>
		            		<div class="select-wrap">
		                  <div class="icon"><span class="ion-ios-arrow-down"></span></div>
								{{form.user_city}}
		                </div>
		            	</div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                	<label >Address</label>
							{{form.user_address}}
	                </div>
		            </div>
		            <div class="col-md-6">
		            	<div class="form-group">
		            		<label >Postcode / ZIP *</label>
							{{form.user_postcode}}
							<div style="font-size: 10px">{{ form.user_postcode.errors }}</div>
	                </div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
	                <div class="form-group">
	                	<label >Phone</label>
						{{form.phonenumber}}
						<div style="font-size: 10px">{{ form.phonenumber.errors }}</div>
	                </div>
	              </div>
	              <div class="col-md-6">
	                <div class="form-group">
	                	<label >Email Address</label>
						{{form.email}}
						<div style="font-size: 10px">{{ form.email.errors }}</div>
	                </div>

                </div>
                <div class="w-100"></div>

                <div class="col-md-12">
                	<div class="form-group mt-4">
					<button class="btn btn-primary py-3 px-4 btn-block" type="submit">accept information</button>
									</div>
                </div>
	            </div>
	          </form><!-- END -->

	          <div class="row mt-5 pt-3 d-flex">
	          	<div class="col-md-6 d-flex">
	          		<div class="cart-detail cart-total ftco-bg-dark p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Cart Total</h3>
	          			<p class="d-flex">

		    						<span>Subtotal</span>
		    						<span>${{session_data.subtotal}}</span>
		    					</p>
		    					<p class="d-flex">
		    						<span>Delivery</span>
		    						<span>${{session_data.delivery_cost}}</span>
		    					</p>
		    					<p class="d-flex">
		    						<span>Discount</span>

		    						<span>{{session_data.discount_total}}%</span>

		    					</p>
		    					<hr>
		    					<p class="d-flex total-price">
		    						<span>Total</span>
		    						<span>${{session_data.total}}</span>
		    					</p>

								</div>
	          	</div>
	          	<div class="col-md-6">
	          		<div class="cart-detail ftco-bg-dark p-3 p-md-4">
						<form action="{% url 'cafe:payment_paid' 'paid' %}"  method="post" >
							{% csrf_token %}
	          			<h3 class="billing-heading mb-4">Delivery Time</h3>

									<div class="form-group">
										<div class="col-md-12">
											{{delivery_form.delivery_date.label_tag}}
											<div class="select-wrap billing-form">
												{{delivery_form.delivery_date}}
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
												{{delivery_form.delivery_time.label_tag}}
												<div class="select-wrap">
												{{delivery_form.delivery_time}}
											</div>
										</div>
									</div>

									<button type="submit" class="btn btn-primary py-3 px-4">Place an order</button>
							</form>
								</div>

	          	</div>
	          </div>

          </div> <!-- .col-md-8 -->




          <div class="col-xl-4 sidebar ftco-animate fadeInUp ftco-animated">
			  <div class="sidebar-box">
              <form class="search-form" action="{% url 'cafe:cart-receipt' 'payment' %}" method="get" >
                <div class="form-group">
                	<div class="icon">
	                  <span class="icon-search"></span>

                  </div>
					{{search.search_form.as_p}}
                </div>

              </form>
            </div>
			  {% if search.items %}
			<h2 class="search-form">Search Results</h2>
			<ul>
			  {% for item in search.items %}
				<li>
				  <a href="{% url 'cafe:detail_item' item.id %}">{{ item.title }}</a>
				</li>
			  {% endfor %}
			</ul>
		  {% endif %}
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
				  <ul>
				    {% for item in category_item_counts %}
				  <li><a href="{% url 'cafe:cat_item' item.title %}" target="_blank">{{ item.title }} <span>({{item.item_count}})</span></a></li>
				  {% endfor %}
					  </ul>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Recent Blog</h3>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({% static 'images/image_2.jpg' %});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({% static 'images/image_3.jpg' %});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Tag Cloud</h3>
              <div class="tagcloud">
				   {% for tag in all_tag %}
        			<a href="{% url 'cafe:items_by_tag' tag_slug=tag %}" target="_blank">
            			{{ tag }}
       				 </a>
				  {% if not forloop.last %}{% endif %}
   				 {% endfor %}






<!--                <a href="#" class="tag-cloud-link">dish</a>-->
<!--                <a href="#" class="tag-cloud-link">menu</a>-->
<!--                <a href="#" class="tag-cloud-link">food</a>-->
<!--                <a href="#" class="tag-cloud-link">sweet</a>-->
<!--                <a href="#" class="tag-cloud-link">tasty</a>-->
<!--                <a href="#" class="tag-cloud-link">delicious</a>-->
<!--                <a href="#" class="tag-cloud-link">desserts</a>-->
<!--                <a href="#" class="tag-cloud-link">drinks</a>-->
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->

  <script>
		$(document).ready(function(){

		var quantitiy=0;
		   $('.quantity-right-plus').click(function(e){
		        
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		            
		            $('#quantity').val(quantity + 1);

		          
		            // Increment
		        
		    });

		     $('.quantity-left-minus').click(function(e){
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		      
		            // Increment
		            if(quantity>0){
		            $('#quantity').val(quantity - 1);
		            }
		    });
		    
		});
	</script>
{% endblock %}

cafe/templates/payment_done.html
{% extends 'base_account.html' %}
{% load static %}
{% block title %}reset_password{% endblock %}
  {% block content %}
     <section class="ftco-section">
        <div class="container">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-xl-10">
                    <div class="card " style="border-radius: 1rem; background: linear-gradient(to bottom, #251001, #836a4b);">
                        <div class="row m-3 g-0">
                            <div class="col-md-6 col-lg-5 d-none d-md-block">
                                <!-- Center the image within the left column -->
                                <div class="d-flex align-items-center  m-3 h-100">
                                    <img src="{% static 'images/menu-4.jpg' %}" alt="login form" class="img-fluid"
                                        style="border-radius: 1rem 0 0 1rem; margin: 0 auto;" />
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-7 d-flex align-items-center" ;">
                                 <h1 class="h1 fw-bold mb-0">Your order has been successfully placed  </h1>

                            </div>

                        </div>

                        <button type="submit" class="btn  btn-lg btn-block"
                                style="background-color: #765E41 !important; border: none !important; color:#291304 !important; font-size: large !important;">
                            <a href="{% url 'cafe:cart' %}">Back To Cart</a></button>
                    </div>
                </div>
            </div>
        </div>
    </section>
  {% endblock %}